version: '3'

networks:
        nginx-net:
                driver: bridge

services:
        nginx:
                image: nginx
                volumes:
                        - ./nginx.conf:/etc/nginx/nginx.conf
                ports:
                        - 8080:80
                networks:
                        - nginx-net

        mysql:
                image: mysql:5.7
                command: --innodb-use-native-aio=0l
                restart: always
                tty: true
                volumes:
                        - ./mysql:/var/lib/mysql
                environment:
                        - MYSQL_DATABASE=nodedb
                        - MYSQL_ROOT_PASSWORD=root
                networks:
                        - nginx-net

        node-1:
                build:
                        context: ./node
                        dockerfile: ./Dockerfile.prod
                networks:
                        - nginx-net
                volumes:
                        - ./node:/usr/src/app
                tty: true
                # entrypoint: dockerize -wait tcp://mysql:3306 -timeout 20s docker-entrypoint.sh
                entrypoint: dockerize -wait tcp://mysql:3306 -timeout 20s node index.js
                depends_on:
                        - mysql
